# .github/workflows/preview.yml
name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions: write-all


jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      run: | 
        echo "1111"
