# .github/workflows/preview.yml
name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - 'main'

permissions: write-all


jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          #persist-credentials: false
          #fetch-depth: 0
      - run: echo github.event.action #npm i && npm run build
        if: github.event.action != 'closed'

      - name: Extract PR details
        id: pr
        run: |
          PR_ID=pr-${{ github.event.pull_request.number }}
          PREVIEW_PATH=previews/${PR_ID}
          echo "::set-output name=PR_ID::${PR_ID}"

      - name: Commit files
        run: | 
          git remote -v 
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          echo abc > abc
          git add -A
          git commit -am "update"

          git push --set-upstream origin gh-pages
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

          #      - name: Push changes
          #        uses: ad-m/github-push-action@master
          #        with:
          #          github_token: ${{ secrets.GITHUB_TOKEN }}

#      - uses: rossjrw/pr-preview-action@v1
#        with:
#          source-dir: .
#          preview-branch: gh-pages
#          umbrella-dir: pr-preview
#          action: auto

