# .github/workflows/preview.yml
name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write


jobs:
  test-deploy:
    name: Test deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: checkout list conetents
        run: |
          ls -al

      - name: "Upload generated content"
        uses: actions/upload-artifact@v2
        with:
          name: site
          if-no-files-found: error
          path: ./

  deploy-preview:
    runs-on: ubuntu-latest
    needs:
      - test-deploy
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          #persist-credentials: false
          #fetch-depth: 0
      - run: echo github.event.action #npm i && npm run build
        if: github.event.action != 'closed'

      - name: Extract PR details
        id: pr
        run: |
          PR_ID=pr-${{ github.event.pull_request.number }}
          PREVIEW_PATH=previews/${PR_ID}
          echo "::set-output name=PR_ID::${PR_ID}"

      - name: "Remove preview build directory"
        run: rm -rf ${{ steps.pr.outputs.PR_ID }}
      - name: "Create preview build directory"
        run: mkdir -p ${{ steps.pr.outputs.PR_ID }}
      - name: "Download generated content"
        uses: actions/download-artifact@v2
        with:
          name: site
          path: ${{ steps.pr.outputs.PR_ID }}

      - name: PR preview details
        run:
          echo "you can preview the PR at https://keepingnetwork.github.io/website/${{ steps.pr.outputs.PR_ID }}/"

      - name: "Commit changes"
        run: |
          set -euo pipefail

          # Debug information
          echo "Current directory: $(pwd)"
          echo "Contents of the repository:"
          ls -al
          tree
          echo "Git status:"
          git status
          
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git add .
          
          
          if ! git diff-index --quiet HEAD --; then
            # Debug information
            echo "Changes detected. Committing and pushing changes."

            commit_message="Adding or updating preview build for PR ${{ steps.pr.outputs.PR_ID }}"
          
            # Debug message
            echo "Commit message: $commit_message"
          
            # Commit changes
            git commit -m "$commit_message"
          
            # Check if commit was successful
            if [ $? -eq 0 ]; then
              # Debug information
              echo "Commit successful. Pushing changes."
          
              # Push changes
              git push --set-upstream origin gh-pages
          
              # Check if push was successful
              if [ $? -eq 0 ]; then
                # Debug information
                echo "Push successful."
              else
                # Debug information
                echo "Error: Push failed."
              fi
            else
              # Debug information
              echo "Error: Commit failed."
            fi
          else
            # Debug information
            echo "No changes found."
          fi
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Send comment to PR"
        continue-on-error: true
        run: |
          set -euo pipefail
          echo "Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://keepingnetwork.github.io/website/${{ steps.pr.outputs.PR_ID }}/ ." >/tmp/comment
          gh pr comment ${{ github.event.pull_request.number }} -F /tmp/comment
        env:
          # USER_TOKEN: "${{ secrets.USER_TOKEN }}"
          GH_TOKEN: "${{ github.token }}"

#      - uses: rossjrw/pr-preview-action@v1
#        with:
#          source-dir: .
#          preview-branch: gh-pages
#          umbrella-dir: pr-preview
#          action: auto

